import type { CodeProjector } from "../contracts/code-projection.contract.js";
import type {
  DeclarativeTypeScriptArtifact,
  DeclarativeTypeScriptProjection,
  TypeScriptClassMember,
  TypeScriptDeclaration,
  TypeScriptExpression,
  TypeScriptImport,
  TypeScriptInterfaceMember,
  TypeScriptObjectProperty,
  TypeScriptParameter,
  TypeScriptStatement,
  TypeScriptSwitchCase,
} from "../contracts/declarative-code-body.contract.js";
import type { JsonValue } from "../types/json.type.js";

const projectorId = "semantic-kernel/declarative-typescript.v1";

export const declarativeTypeScriptProjector: CodeProjector = Object.freeze({
  projectorId,
  project({ authority }) {
    const declaration = requireProjection(authority);
    return Object.freeze({
      targetId: declaration.targetId,
      artifacts: Object.freeze(declaration.artifacts.map((artifact) => Object.freeze({
        path: artifact.path,
        content: renderArtifact(declaration, artifact),
      }))),
      metadata: Object.freeze({
        projectionId: declaration.projectionId,
        projectionVersion: declaration.version,
        language: "typescript",
        moduleKind: "esm",
      }),
    });
  },
});

function renderArtifact(projection: DeclarativeTypeScriptProjection, artifact: DeclarativeTypeScriptArtifact): string {
  const sections = [
    `// @generated by ${projectorId}; DO NOT EDIT.`,
    `// projection-id: ${projection.projectionId}`,
    "",
    ...(artifact.imports ?? []).map(renderImport),
    ...((artifact.imports?.length ?? 0) > 0 ? [""] : []),
    ...artifact.declarations.flatMap((declaration, index) => [
      renderDeclaration(declaration, 0),
      ...(index === artifact.declarations.length - 1 ? [] : [""]),
    ]),
    "",
  ];
  return sections.join("\n");
}

function renderImport(declaration: TypeScriptImport): string {
  const clauses: string[] = [];
  if (declaration.default !== undefined) clauses.push(identifier(declaration.default));
  if (declaration.namespace !== undefined) clauses.push(`* as ${identifier(declaration.namespace)}`);
  if (declaration.named !== undefined && declaration.named.length > 0) {
    clauses.push(`{ ${declaration.named.map((entry) => {
      const imported = identifier(entry.imported);
      const local = entry.local === undefined ? "" : ` as ${identifier(entry.local)}`;
      return `${entry.typeOnly === true ? "type " : ""}${imported}${local}`;
    }).join(", ")} }`);
  }
  const typeOnly = declaration.typeOnly === true ? "type " : "";
  if (clauses.length === 0) return `import ${JSON.stringify(declaration.from)};`;
  return `import ${typeOnly}${clauses.join(", ")} from ${JSON.stringify(declaration.from)};`;
}

function renderDeclaration(declaration: TypeScriptDeclaration, depth: number): string {
  const prefix = "export" in declaration && declaration.export === true ? "export " : "";
  switch (declaration.kind) {
    case "function": {
      const defaultKeyword = declaration.default === true ? "default " : "";
      const asyncKeyword = declaration.async === true ? "async " : "";
      const result = declaration.returnType === undefined ? "" : `: ${typeText(declaration.returnType)}`;
      return `${prefix}${defaultKeyword}${asyncKeyword}function ${identifier(declaration.name)}(${renderParameters(declaration.parameters)})${result} ${renderBlock(declaration.body, depth)}`;
    }
    case "variable": {
      const annotation = declaration.type === undefined ? "" : `: ${typeText(declaration.type)}`;
      return `${prefix}${declaration.declarationKind} ${identifier(declaration.name)}${annotation} = ${renderExpression(declaration.value, depth)};`;
    }
    case "type-alias": {
      const parameters = declaration.typeParameters === undefined || declaration.typeParameters.length === 0
        ? ""
        : `<${declaration.typeParameters.map(identifier).join(", ")}>`;
      return `${prefix}type ${identifier(declaration.name)}${parameters} = ${typeText(declaration.type)};`;
    }
    case "interface": {
      const heritage = declaration.extends === undefined || declaration.extends.length === 0
        ? ""
        : ` extends ${declaration.extends.map(typeText).join(", ")}`;
      const members = declaration.members.map((member) => `${indent(depth + 1)}${renderInterfaceMember(member)}`).join("\n");
      return `${prefix}interface ${identifier(declaration.name)}${heritage} {\n${members}\n${indent(depth)}}`;
    }
    case "class": {
      const defaultKeyword = declaration.default === true ? "default " : "";
      const heritage = declaration.extends === undefined ? "" : ` extends ${renderExpression(declaration.extends, depth)}`;
      const members = declaration.members.map((member) => `${indent(depth + 1)}${renderClassMember(member, depth + 1)}`).join("\n\n");
      return `${prefix}${defaultKeyword}class ${identifier(declaration.name)}${heritage} {\n${members}\n${indent(depth)}}`;
    }
    case "export-all": return `export * from ${JSON.stringify(declaration.from)};`;
  }
}

function renderInterfaceMember(member: TypeScriptInterfaceMember): string {
  const optional = member.optional === true ? "?" : "";
  if (member.kind === "property") {
    return `${member.readonly === true ? "readonly " : ""}${propertyName(member.name)}${optional}: ${typeText(member.type)};`;
  }
  return `${propertyName(member.name)}${optional}(${renderParameters(member.parameters)}): ${typeText(member.returnType)};`;
}

function renderClassMember(member: TypeScriptClassMember, depth: number): string {
  if (member.kind === "constructor") {
    return `constructor(${renderParameters(member.parameters)}) ${renderBlock(member.body, depth)}`;
  }
  const visibility = member.visibility === undefined ? "" : `${member.visibility} `;
  const staticKeyword = member.static === true ? "static " : "";
  if (member.kind === "property") {
    const readonlyKeyword = member.readonly === true ? "readonly " : "";
    const annotation = member.type === undefined ? "" : `: ${typeText(member.type)}`;
    const initializer = member.value === undefined ? "" : ` = ${renderExpression(member.value, depth)}`;
    return `${visibility}${staticKeyword}${readonlyKeyword}${propertyName(member.name)}${annotation}${initializer};`;
  }
  const asyncKeyword = member.async === true ? "async " : "";
  const result = member.returnType === undefined ? "" : `: ${typeText(member.returnType)}`;
  return `${visibility}${staticKeyword}${asyncKeyword}${propertyName(member.name)}(${renderParameters(member.parameters)})${result} ${renderBlock(member.body, depth)}`;
}

function renderParameters(parameters: readonly TypeScriptParameter[]): string {
  return parameters.map((parameter) => {
    const optional = parameter.optional === true ? "?" : "";
    const annotation = parameter.type === undefined ? "" : `: ${typeText(parameter.type)}`;
    return `${identifier(parameter.name)}${optional}${annotation}`;
  }).join(", ");
}

function renderBlock(statements: readonly TypeScriptStatement[], depth: number): string {
  if (statements.length === 0) return "{}";
  return `{\n${statements.map((statement) => renderStatement(statement, depth + 1)).join("\n")}\n${indent(depth)}}`;
}

function renderStatement(statement: TypeScriptStatement, depth: number): string {
  const padding = indent(depth);
  switch (statement.kind) {
    case "variable": {
      const annotation = statement.type === undefined ? "" : `: ${typeText(statement.type)}`;
      return `${padding}${statement.declarationKind} ${identifier(statement.name)}${annotation} = ${renderExpression(statement.value, depth)};`;
    }
    case "expression": return `${padding}${renderExpression(statement.expression, depth)};`;
    case "return": return `${padding}return${statement.expression === undefined ? "" : ` ${renderExpression(statement.expression, depth)}`};`;
    case "throw": return `${padding}throw ${renderExpression(statement.expression, depth)};`;
    case "if": {
      const otherwise = statement.otherwise === undefined ? "" : ` else ${renderBlock(statement.otherwise, depth)}`;
      return `${padding}if (${renderExpression(statement.condition, depth)}) ${renderBlock(statement.then, depth)}${otherwise}`;
    }
    case "for-of": {
      const awaitKeyword = statement.await === true ? " await" : "";
      return `${padding}for${awaitKeyword} (${statement.declarationKind} ${identifier(statement.name)} of ${renderExpression(statement.iterable, depth)}) ${renderBlock(statement.body, depth)}`;
    }
    case "while": return `${padding}while (${renderExpression(statement.condition, depth)}) ${renderBlock(statement.body, depth)}`;
    case "try": {
      const catchClause = statement.catch === undefined
        ? ""
        : ` catch (${identifier(statement.catch.binding)}) ${renderBlock(statement.catch.body, depth)}`;
      const finallyClause = statement.finally === undefined ? "" : ` finally ${renderBlock(statement.finally, depth)}`;
      return `${padding}try ${renderBlock(statement.body, depth)}${catchClause}${finallyClause}`;
    }
    case "switch":
      return `${padding}switch (${renderExpression(statement.expression, depth)}) {\n${statement.cases.map((entry) => renderSwitchCase(entry, depth + 1)).join("\n")}\n${padding}}`;
    case "break": return `${padding}break;`;
    case "continue": return `${padding}continue;`;
    case "block": return `${padding}${renderBlock(statement.body, depth)}`;
  }
}

function renderSwitchCase(entry: TypeScriptSwitchCase, depth: number): string {
  const label = entry.test === undefined ? "default" : `case ${renderExpression(entry.test, depth)}`;
  const body = entry.body.map((statement) => renderStatement(statement, depth + 1)).join("\n");
  return `${indent(depth)}${label}:\n${body}`;
}

function renderExpression(expression: TypeScriptExpression, depth: number): string {
  switch (expression.kind) {
    case "literal": return JSON.stringify(expression.value);
    case "identifier": return identifier(expression.name);
    case "member": {
      const object = renderExpression(expression.object, depth);
      return /^[A-Za-z_$][A-Za-z0-9_$]*$/u.test(expression.property)
        ? `${object}${expression.optional === true ? "?." : "."}${expression.property}`
        : `${object}${expression.optional === true ? "?." : ""}[${JSON.stringify(expression.property)}]`;
    }
    case "index": return `${renderExpression(expression.object, depth)}${expression.optional === true ? "?." : ""}[${renderExpression(expression.index, depth)}]`;
    case "call": return `${renderExpression(expression.callee, depth)}${expression.optional === true ? "?." : ""}(${(expression.arguments ?? []).map((argument) => renderExpression(argument, depth)).join(", ")})`;
    case "new": return `new ${renderExpression(expression.callee, depth)}(${(expression.arguments ?? []).map((argument) => renderExpression(argument, depth)).join(", ")})`;
    case "await": return `await ${renderExpression(expression.expression, depth)}`;
    case "assign": return `${renderAssignable(expression.target, depth)} ${expression.operator} ${renderExpression(expression.value, depth)}`;
    case "update": return expression.prefix === true
      ? `${expression.operator}${renderAssignable(expression.operand, depth)}`
      : `${renderAssignable(expression.operand, depth)}${expression.operator}`;
    case "unary": return expression.operator === "typeof" || expression.operator === "void"
      ? `${expression.operator} ${renderExpression(expression.operand, depth)}`
      : `${expression.operator}${renderExpression(expression.operand, depth)}`;
    case "binary": return `(${renderExpression(expression.left, depth)} ${expression.operator} ${renderExpression(expression.right, depth)})`;
    case "conditional": return `(${renderExpression(expression.condition, depth)} ? ${renderExpression(expression.then, depth)} : ${renderExpression(expression.otherwise, depth)})`;
    case "array": return `[${expression.items.map((item) => renderExpression(item, depth)).join(", ")}]`;
    case "object": return renderObject(expression.properties, depth);
    case "arrow": {
      const asyncKeyword = expression.async === true ? "async " : "";
      const body = Array.isArray(expression.body)
        ? renderBlock(expression.body as readonly TypeScriptStatement[], depth)
        : renderExpression(expression.body as TypeScriptExpression, depth);
      return `${asyncKeyword}(${renderParameters(expression.parameters)}) => ${body}`;
    }
    case "template": return `\`${expression.parts.map((part) => typeof part === "string"
      ? part.replaceAll("\\", "\\\\").replaceAll("`", "\\`").replaceAll("${", "\\${")
      : `\${${renderExpression(part, depth)}}`).join("")}\``;
    case "as": return `(${renderExpression(expression.expression, depth)} as ${typeText(expression.type)})`;
    case "spread": return `...${renderExpression(expression.expression, depth)}`;
  }
}

function renderObject(properties: readonly TypeScriptObjectProperty[], depth: number): string {
  if (properties.length === 0) return "{}";
  return `{ ${properties.map((property) => {
    if (property.kind === "spread") return `...${renderExpression(property.expression, depth)}`;
    if (property.shorthand === true) {
      if (property.value.kind !== "identifier" || property.value.name !== property.name) invalid("Shorthand property must reference the same identifier.");
      return identifier(property.name);
    }
    return `${propertyName(property.name)}: ${renderExpression(property.value, depth)}`;
  }).join(", ")} }`;
}

function renderAssignable(expression: TypeScriptExpression, depth: number): string {
  if (expression.kind !== "identifier" && expression.kind !== "member" && expression.kind !== "index") {
    invalid(`Expression kind ${expression.kind} is not an assignment target.`);
  }
  return renderExpression(expression, depth);
}

function requireProjection(value: JsonValue): DeclarativeTypeScriptProjection {
  if (!isRecord(value) || value.projectionType !== "declarative-typescript-projection.v1") {
    invalid("projectionType must be declarative-typescript-projection.v1.");
  }
  requireKeys(value, ["projectionType", "projectionId", "version", "targetId", "artifacts"], "projection");
  if (!isIdentity(value.projectionId) || value.targetId !== "typescript-esm") invalid("Projection and target identities are invalid.");
  if (typeof value.version !== "string" || !/^(?!0\.0\.0$)\d+\.\d+\.\d+$/u.test(value.version)) invalid("Version is invalid.");
  if (!Array.isArray(value.artifacts) || value.artifacts.length === 0) invalid("At least one artifact is required.");
  const paths = new Set<string>();
  for (const artifact of value.artifacts) validateArtifact(artifact, paths);
  const declaration = value as unknown as DeclarativeTypeScriptProjection;
  for (const artifact of declaration.artifacts) renderArtifact(declaration, artifact);
  return declaration;
}

function validateArtifact(value: JsonValue, paths: Set<string>): void {
  if (!isRecord(value) || typeof value.path !== "string" || !/^.+\.(?:ts|mts|cts)$/u.test(value.path)) invalid("Every artifact requires a TypeScript path.");
  requireKeys(value, ["path", "imports", "declarations"], `artifact ${value.path}`);
  if (paths.has(value.path)) invalid(`Duplicate artifact path: ${value.path}.`);
  paths.add(value.path);
  if (value.imports !== undefined && !Array.isArray(value.imports)) invalid(`Artifact ${value.path} imports must be an array.`);
  if (!Array.isArray(value.declarations) || value.declarations.length === 0) invalid(`Artifact ${value.path} requires declarations.`);
  for (const entry of value.imports ?? []) validateImportNode(entry);
  for (const entry of value.declarations) validateDeclarationNode(entry);
}

function validateImportNode(value: JsonValue): void {
  const node = recordNode(value, "import");
  requireKeys(node, ["kind", "from", "typeOnly", "default", "namespace", "named"], "import");
  if (node.kind !== "import" || typeof node.from !== "string") invalid("Import kind and module specifier are required.");
  if (node.named !== undefined) {
    if (!Array.isArray(node.named)) invalid("Import named must be an array.");
    for (const entry of node.named) {
      const named = recordNode(entry, "named import");
      requireKeys(named, ["imported", "local", "typeOnly"], "named import");
    }
  }
}

function validateDeclarationNode(value: JsonValue): void {
  const node = recordNode(value, "declaration");
  switch (node.kind) {
    case "function":
      requireKeys(node, ["kind", "name", "export", "default", "async", "parameters", "returnType", "body"], "function declaration");
      validateParameters(node.parameters);
      validateStatements(node.body);
      return;
    case "variable":
      requireKeys(node, ["kind", "name", "export", "declarationKind", "type", "value"], "variable declaration");
      requireOneOf(node.declarationKind, ["const", "let"], "variable declaration kind");
      validateExpressionNode(node.value);
      return;
    case "type-alias":
      requireKeys(node, ["kind", "name", "export", "typeParameters", "type"], "type alias");
      return;
    case "interface":
      requireKeys(node, ["kind", "name", "export", "extends", "members"], "interface declaration");
      for (const member of arrayNode(node.members, "interface members")) validateInterfaceMemberNode(member);
      return;
    case "class":
      requireKeys(node, ["kind", "name", "export", "default", "extends", "members"], "class declaration");
      if (node.extends !== undefined) validateExpressionNode(node.extends);
      for (const member of arrayNode(node.members, "class members")) validateClassMemberNode(member);
      return;
    case "export-all":
      requireKeys(node, ["kind", "from"], "export-all declaration");
      return;
    default:
      invalid(`Unsupported declaration kind: ${String(node.kind)}.`);
  }
}

function validateInterfaceMemberNode(value: JsonValue): void {
  const node = recordNode(value, "interface member");
  if (node.kind === "property") {
    requireKeys(node, ["kind", "name", "type", "optional", "readonly"], "interface property");
    return;
  }
  if (node.kind === "method") {
    requireKeys(node, ["kind", "name", "parameters", "returnType", "optional"], "interface method");
    validateParameters(node.parameters);
    return;
  }
  invalid(`Unsupported interface member kind: ${String(node.kind)}.`);
}

function validateClassMemberNode(value: JsonValue): void {
  const node = recordNode(value, "class member");
  if (node.kind === "property") {
    requireKeys(node, ["kind", "name", "visibility", "static", "readonly", "type", "value"], "class property");
    if (node.value !== undefined) validateExpressionNode(node.value);
    return;
  }
  if (node.kind === "constructor") {
    requireKeys(node, ["kind", "parameters", "body"], "class constructor");
    validateParameters(node.parameters);
    validateStatements(node.body);
    return;
  }
  if (node.kind === "method") {
    requireKeys(node, ["kind", "name", "visibility", "static", "async", "parameters", "returnType", "body"], "class method");
    validateParameters(node.parameters);
    validateStatements(node.body);
    return;
  }
  invalid(`Unsupported class member kind: ${String(node.kind)}.`);
}

function validateParameters(value: JsonValue | undefined): void {
  for (const entry of arrayNode(value, "parameters")) {
    const parameter = recordNode(entry, "parameter");
    requireKeys(parameter, ["name", "type", "optional"], "parameter");
  }
}

function validateStatements(value: JsonValue | undefined): void {
  for (const entry of arrayNode(value, "statements")) validateStatementNode(entry);
}

function validateStatementNode(value: JsonValue): void {
  const node = recordNode(value, "statement");
  switch (node.kind) {
    case "variable":
      requireKeys(node, ["kind", "declarationKind", "name", "type", "value"], "variable statement");
      requireOneOf(node.declarationKind, ["const", "let"], "variable statement kind");
      validateExpressionNode(node.value);
      return;
    case "expression":
      requireKeys(node, ["kind", "expression"], "expression statement");
      validateExpressionNode(node.expression);
      return;
    case "return":
      requireKeys(node, ["kind", "expression"], "return statement");
      if (node.expression !== undefined) validateExpressionNode(node.expression);
      return;
    case "throw":
      requireKeys(node, ["kind", "expression"], "throw statement");
      validateExpressionNode(node.expression);
      return;
    case "if":
      requireKeys(node, ["kind", "condition", "then", "otherwise"], "if statement");
      validateExpressionNode(node.condition);
      validateStatements(node.then);
      if (node.otherwise !== undefined) validateStatements(node.otherwise);
      return;
    case "for-of":
      requireKeys(node, ["kind", "declarationKind", "name", "iterable", "body", "await"], "for-of statement");
      requireOneOf(node.declarationKind, ["const", "let"], "for-of declaration kind");
      validateExpressionNode(node.iterable);
      validateStatements(node.body);
      return;
    case "while":
      requireKeys(node, ["kind", "condition", "body"], "while statement");
      validateExpressionNode(node.condition);
      validateStatements(node.body);
      return;
    case "try":
      requireKeys(node, ["kind", "body", "catch", "finally"], "try statement");
      validateStatements(node.body);
      if (node.catch === undefined && node.finally === undefined) invalid("Try statement requires catch or finally.");
      if (node.catch !== undefined) {
        const catchNode = recordNode(node.catch, "catch clause");
        requireKeys(catchNode, ["binding", "body"], "catch clause");
        validateStatements(catchNode.body);
      }
      if (node.finally !== undefined) validateStatements(node.finally);
      return;
    case "switch":
      requireKeys(node, ["kind", "expression", "cases"], "switch statement");
      validateExpressionNode(node.expression);
      for (const entry of arrayNode(node.cases, "switch cases")) {
        const switchCase = recordNode(entry, "switch case");
        requireKeys(switchCase, ["test", "body"], "switch case");
        if (switchCase.test !== undefined) validateExpressionNode(switchCase.test);
        validateStatements(switchCase.body);
      }
      return;
    case "break":
    case "continue":
      requireKeys(node, ["kind"], `${node.kind} statement`);
      return;
    case "block":
      requireKeys(node, ["kind", "body"], "block statement");
      validateStatements(node.body);
      return;
    default:
      invalid(`Unsupported statement kind: ${String(node.kind)}.`);
  }
}

function validateExpressionNode(value: JsonValue | undefined): void {
  const node = recordNode(value, "expression");
  switch (node.kind) {
    case "literal":
      requireKeys(node, ["kind", "value"], "literal expression");
      return;
    case "identifier":
      requireKeys(node, ["kind", "name"], "identifier expression");
      return;
    case "member":
      requireKeys(node, ["kind", "object", "property", "optional"], "member expression");
      validateExpressionNode(node.object);
      return;
    case "index":
      requireKeys(node, ["kind", "object", "index", "optional"], "index expression");
      validateExpressionNode(node.object);
      validateExpressionNode(node.index);
      return;
    case "call":
    case "new":
      requireKeys(node, ["kind", "callee", "arguments", ...(node.kind === "call" ? ["optional"] : [])], `${node.kind} expression`);
      validateExpressionNode(node.callee);
      for (const argument of arrayNode(node.arguments ?? [], "arguments")) validateExpressionNode(argument);
      return;
    case "await":
    case "spread":
      requireKeys(node, ["kind", "expression"], `${node.kind} expression`);
      validateExpressionNode(node.expression);
      return;
    case "assign":
      requireKeys(node, ["kind", "operator", "target", "value"], "assignment expression");
      requireOneOf(node.operator, ["=", "+=", "-=", "*=", "/="], "assignment operator");
      validateExpressionNode(node.target);
      validateExpressionNode(node.value);
      return;
    case "update":
      requireKeys(node, ["kind", "operator", "operand", "prefix"], "update expression");
      requireOneOf(node.operator, ["++", "--"], "update operator");
      validateExpressionNode(node.operand);
      return;
    case "unary":
      requireKeys(node, ["kind", "operator", "operand"], "unary expression");
      requireOneOf(node.operator, ["!", "-", "+", "typeof", "void"], "unary operator");
      validateExpressionNode(node.operand);
      return;
    case "binary":
      requireKeys(node, ["kind", "operator", "left", "right"], "binary expression");
      requireOneOf(node.operator, ["===", "!==", "==", "!=", ">", ">=", "<", "<=", "+", "-", "*", "/", "%", "&&", "||", "??", "in", "instanceof"], "binary operator");
      validateExpressionNode(node.left);
      validateExpressionNode(node.right);
      return;
    case "conditional":
      requireKeys(node, ["kind", "condition", "then", "otherwise"], "conditional expression");
      validateExpressionNode(node.condition);
      validateExpressionNode(node.then);
      validateExpressionNode(node.otherwise);
      return;
    case "array":
      requireKeys(node, ["kind", "items"], "array expression");
      for (const item of arrayNode(node.items, "array items")) validateExpressionNode(item);
      return;
    case "object":
      requireKeys(node, ["kind", "properties"], "object expression");
      for (const entry of arrayNode(node.properties, "object properties")) {
        const property = recordNode(entry, "object property");
        if (property.kind === "property") {
          requireKeys(property, ["kind", "name", "value", "shorthand"], "object property");
          validateExpressionNode(property.value);
        } else if (property.kind === "spread") {
          requireKeys(property, ["kind", "expression"], "object spread");
          validateExpressionNode(property.expression);
        } else {
          invalid(`Unsupported object property kind: ${String(property.kind)}.`);
        }
      }
      return;
    case "arrow":
      requireKeys(node, ["kind", "async", "parameters", "body"], "arrow expression");
      validateParameters(node.parameters);
      if (Array.isArray(node.body)) validateStatements(node.body);
      else validateExpressionNode(node.body);
      return;
    case "template":
      requireKeys(node, ["kind", "parts"], "template expression");
      for (const part of arrayNode(node.parts, "template parts")) if (typeof part !== "string") validateExpressionNode(part);
      return;
    case "as":
      requireKeys(node, ["kind", "expression", "type"], "as expression");
      validateExpressionNode(node.expression);
      return;
    default:
      invalid(`Unsupported expression kind: ${String(node.kind)}.`);
  }
}

function requireKeys(
  value: Readonly<Record<string, JsonValue>>,
  allowed: readonly string[],
  location: string,
): void {
  const unknown = Object.keys(value).filter((key) => !allowed.includes(key));
  if (unknown.length > 0) invalid(`${location} contains unsupported fields: ${unknown.join(", ")}.`);
}

function recordNode(value: JsonValue | undefined, location: string): Readonly<Record<string, JsonValue>> {
  if (!isRecord(value)) invalid(`${location} must be an object.`);
  return value;
}

function arrayNode(value: JsonValue | undefined, location: string): readonly JsonValue[] {
  if (!Array.isArray(value)) invalid(`${location} must be an array.`);
  return value;
}

function requireOneOf(value: JsonValue | undefined, allowed: readonly string[], location: string): void {
  if (typeof value !== "string" || !allowed.includes(value)) invalid(`${location} must be one of: ${allowed.join(", ")}.`);
}

function identifier(value: string): string {
  if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/u.test(value)) invalid(`Invalid TypeScript identifier: ${value}.`);
  return value;
}

function propertyName(value: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/u.test(value) ? value : JSON.stringify(value);
}

function typeText(value: string): string {
  if (value.length === 0 || /[\r\n;{}]/u.test(value) || /\/[/*]/u.test(value)) invalid(`Unsafe TypeScript type text: ${value}.`);
  return value;
}

function indent(depth: number): string {
  return "  ".repeat(depth);
}

function isIdentity(value: unknown): value is string {
  return typeof value === "string" && /^[a-z0-9]+(?:-[a-z0-9]+)*$/u.test(value);
}

function isRecord(value: unknown): value is Readonly<Record<string, JsonValue>> {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function invalid(message: string): never {
  throw new Error(`Invalid declarative TypeScript authority: ${message}`);
}
